version: "3.8"
services:
  start-server:
    image: buildpack-deps:bullseye-curl
    volumes:
      - ../:/project
    ports:
      - 80:80
      - 3090:3090
    working_dir: /project
    command:
      bash -c '
        [ -d ./dist ] &&
        cd /project/dist/${GO_TARGET_OS}/${GO_TARGET_ARCH}/server &&
        chmod +x ./slash_mochi_server &&
        ./slash_mochi_server'
