version: "3.8"
services:
  start-server:
    image: buildpack-deps:bullseye-curl
    volumes:
      - ../:/project
    ports:
      - 3080:3080
      - 3081:3081
    working_dir: /project
    command:
      bash -c '
        [ -d ./dist ] &&
        chmod +x /project/dist/${GO_TARGET_OS}/${GO_TARGET_ARCH}/server/slash_mochi_server &&
        /project/dist/${GO_TARGET_OS}/${GO_TARGET_ARCH}/server/slash_mochi_server -WebServerPort 3080 -ConnectServerPort 3081'
