services:
  buf-builder:
    image: whoatemyapplepie/slash-mochi-apps-builder:${ENV_TOOLS_VERSION}
    build:
      context: apps_builder
      args:
        - GO_VERSION=${GO_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ../:/project
    working_dir: /project
    command: bash -c "buf mod init"
