version: "3.8"
services:
  node_go_editor:
    image: whoatemyapplepie/slash-mochi-buf-builder:0.1.0
    build:
      context: buf_builder
      args:
        - GO_VERSION=${GO_VERSION}
        - GO_BUILDER_OS=${GO_BUILDER_OS}
        - GO_BUILDER_ARCH=${GO_BUILDER_ARCH}
        - NODE_VERSION=${NODE_VERSION}
        - NODE_BUILDER_OS=${NODE_BUILDER_OS}
        - NODE_BUILDER_ARCH=${NODE_BUILDER_ARCH}
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3081:3081
    volumes:
      - ../:/project
    working_dir: /project
    tty: true
