import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react'
import { TestService } from '@/connect/test_connect'
import { useClient } from '@/connect_client/useClient'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const connectClient = useClient(TestService)
  const [loopbackResult, setLoopbackResult] = useState("")
  const [clickCount, setClickCount] = useState(0)

  function DoLoopbackTest(message: string): void {
    connectClient.loopback({
      message: message + clickCount,
    }).then((res) => {
      setLoopbackResult(res.message)
    })
    setClickCount(clickCount + 1)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <div className='loopback-result'>{loopbackResult}</div>

        <div className={styles.center}>
          <button onClick={(event) => DoLoopbackTest("hoge-")}>Loopback</button>
        </div>
      </main>
    </>
  )
}
