import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react'
import { createPromiseClient } from '@connectrpc/connect'
import { createConnectTransport } from '@connectrpc/connect-web'
import { TestService } from '@/../../../../gen/es/slash_mochi/v1/test/test_connect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const transport = createConnectTransport({
    baseUrl: "http://localhost:3081",
  })
  const connectClient = createPromiseClient(TestService, transport)
  const [loopbackResult, setLoopbackResult] = useState("")
  function DoLoopbackTest(message: string): void {
    connectClient.loopback({
      message: message,
    }).then((res) => {
      // setLoopbackResult(res.message)
      console.log(res)
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <div className='loopback-result'>{loopbackResult}</div>

        <div className={styles.center}>
          <button onClick={(event) => DoLoopbackTest("hoge-")}>Loopback</button>
        </div>
      </main>
    </>
  )
}
